{
  inputs,
  hostSecretPath,
  hostname,
  lib,
  modulesPath,
  secretPath,
  user,
  userSecretPath,
  ...
}:
{
  imports = [
    ../../share/apps/bash.nix
    ../../share/apps/pkgs.nix
    ../../share/settings/console.nix
    ../../share/settings/locale.nix
    ../../share/settings/network.nix
    ../../share/settings/security.nix
    ../../share/settings/system.nix
    ../../share/settings/users.nix
    ../../share/settings/ssh.nix
  ];
}
