[liveimg.first-image]
system = "x86_64-linux"
user = "nixos"
hostname = "first-image"
vlanId = "20"            # separate manage network

[liveimg.second-image]
system = "x86_64-linux"
user = "nixos"
hostname = "second-image"
vlanId = "20"             # separate manage network

[liveimg.livecd]
system = "x86_64-linux"
user = "nixos"
hostname = "nixos-livecd"

[liveimg.netboot]
system = "x86_64-linux"
user = "nixos"
hostname = "nixos-netboot"
