# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  collection-community-general = {
    pname = "collection-community-general";
    version = "9.5.0";
    src = fetchurl {
      url = "https://galaxy.ansible.com/download/community-general-9.5.0.tar.gz";
      sha256 = "sha256-KGSbVdStb26hUON/UfSWefxeOMMxHaq2AI3NYifOUg4=";
    };
  };
  collection-kubernetes-core = {
    pname = "collection-kubernetes-core";
    version = "5.0.0";
    src = fetchurl {
      url = "https://galaxy.ansible.com/download/kubernetes-core-5.0.0.tar.gz";
      sha256 = "sha256-9J5owjSFdbHGu5inEmF9ZZ74VlD2ur2uPYTpz7l3AAk=";
    };
  };
  role-ansible-role-nfs = {
    pname = "role-ansible-role-nfs";
    version = "2.1.0";
    src = fetchFromGitHub {
      owner = "geerlingguy";
      repo = "ansible-role-nfs";
      rev = "2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-hlMoONAi0ek+FJJqIBV1y1IuhcXTUyzSFWGGkNZmVu8=";
    };
    aname = "geerlingguy.nfs";
  };
  role-ha-cluster-pacemaker = {
    pname = "role-ha-cluster-pacemaker";
    version = "45.0.0";
    src = fetchFromGitHub {
      owner = "OndrejHome";
      repo = "ansible.ha-cluster-pacemaker";
      rev = "45.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-fHQw1/gulZjPaf2sKAmAra18FNAly566b41reZ2B8Gw=";
    };
    aname = "ondrejhome.ha-cluster-pacemaker";
  };
  role-pcs-module-2 = {
    pname = "role-pcs-module-2";
    version = "30.0.0";
    src = fetchFromGitHub {
      owner = "OndrejHome";
      repo = "ansible.pcs-modules-2";
      rev = "30.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-B0wqsYuUGb0yl2oj+OO/qkFHVc/8N6W5iwspc/p4Ybc=";
    };
    aname = "ondrejhome.pcs-modules-2";
  };
}
