hostname sks8300-8x
log syslog
service password-encryption
service integrated-vtysh-config
!
frr defaults datacenter
log syslog informational

route-map REDISTRIBUTE_LOOPBACK_INTERFACE permit 10
  match interface lo
exit

ip prefix-list UNDERLAY_IPV4 permit 10.10.10.0/24 ge 32
route-map SET-SRC permit 10
  match ip address prefix-list UNDERLAY_IPV4
  set src 10.10.10.31
exit
ip protocol bgp route-map SET-SRC

route-map WCMP-MAP permit 10
  set extcommunity bandwidth 10
exit

router bgp 65012
  bgp router-id 10.10.10.31
  bgp log-neighbor-changes
  bgp bestpath as-path multipath-relax
  no bgp default ipv4-unicast
  neighbor LEAF peer-group
  neighbor LEAF bfd
  neighbor LEAF remote-as external
  neighbor LEAF advertisement-interval 0
  neighbor LEAF timers 3 9
  neighbor LEAF timers connect 10
  neighbor LEAF capability extended-nexthop
  neighbor eth1 interface peer-group LEAF
  neighbor eth2 interface peer-group LEAF
  neighbor eth3 interface peer-group LEAF
  neighbor eth4 interface peer-group LEAF

  neighbor OVERLAY peer-group
  neighbor OVERLAY remote-as external
  neighbor OVERLAY advertisement-interval 0
  neighbor OVERLAY timers 3 9
  neighbor OVERLAY timers connect 10
  neighbor OVERLAY update-source lo
  neighbor OVERLAY ebgp-multihop
  bgp listen range 10.10.10.0/24 peer-group OVERLAY

  address-family ipv4 unicast
    redistribute connected route-map REDISTRIBUTE_LOOPBACK_INTERFACE
    neighbor LEAF activate
    neighbor LEAF route-map WCMP-MAP out
    maximum-paths 64
  exit-address-family

  address-family l2vpn evpn
    neighbor OVERLAY activate
    advertise-all-vni
  exit-address-family

!
end
