keys:
  - &users:
    - &sumi_mother age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3
    - &sumi_stacia age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl
creation_rules:
  - path_regex: sops/hosts/.*/.*/secrets.yaml
    key_groups:
      - age:
          - *sumi_mother
  - path_regex: sops/keystore/.*/secrets.yaml
    key_groups:
      - age:
          - *sumi_mother
