[default]
[default.extend-words]
hda = "hda"
HD = "HD"

[files]
extend-exclude = [
    "sops",
    "flake.lock",
    "CHANGELOG.md",
    "apps/user/core/ranger/default.nix",
    "apps/user/core/ranger/config/*",
    "apps/user/full/ime/skk-config/libskk/rom-kana/default.json",
]
