apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: PodCIDR
      attributes:
        communities:
          standard:
            - "65200:100"
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      attributes:
        communities:
          standard:
            - "65200:200"
