# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, hostname
, ...
}:
let
  cpu_bender = (pkgs.callPackage ../../utils/consts.nix { }).cpu_bender;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
    };
  };

  # Use crypttab
  # environment.etc.ctypttab.text = ''
  #   # nfsroot /dev/disk/by-partlabel/LUKSNFSROOT /etc/keyfile4nfsroot
  #   # nfs /dev/disk/by-partlabel/LUKSNFS /etc/keyfile4nfs
  # '';
  # environment.etc.keyfile4nfsroot.source = ../keyfiles/nfsroot;
  # environment.etc.keyfile4nfs.source = ../keyfiles/nfsroot;

  fileSystems."/" = {
    device = "PoolCtrl/nixos/root";
    fsType = "zfs";
  };
  fileSystems."/var/lib" = {
    device = "PoolCtrl/nixos/var/lib";
    fsType = "zfs";
  };
  fileSystems."/var/log" = {
    device = "PoolCtrl/nixos/var/log";
    fsType = "zfs";
  };
  fileSystems."/home" = {
    device = "PoolCtrl/nixos/home";
    fsType = "zfs";
  };
  fileSystems."/nix" = {
    device = "PoolCtrl/local/nix";
    fsType = "zfs";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ctrl-boot";
    fsType = "vfat";
  };

  hardware.cpu.${cpu_bender hostname}.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}