# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, hostname
, ...
}:
let
  cpu_bender = (pkgs.callPackage ../../utils/consts.nix { }).cpu_bender;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices = {
        luksroot = {
          device = "/dev/disk/by-partlabel/LUKSROOT";
          preLVM = true;
          allowDiscards = true;
        };
      };
    };
  };

  # Use crypttab
  # environment.etc.ctypttab.text = ''
  #   # nfsroot /dev/disk/by-partlabel/LUKSNFSROOT /etc/keyfile4nfsroot
  #   # nfs /dev/disk/by-partlabel/LUKSNFS /etc/keyfile4nfs
  # '';
  # environment.etc.keyfile4nfsroot.source = ../keyfiles/nfsroot;
  # environment.etc.keyfile4nfs.source = ../keyfiles/nfsroot;

  fileSystems."/" = {
    device = "/dev/disk/by-label/${hostname}-root";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/${hostname}-boot";
    fsType = "vfat";
  };
  # fileSystems."/srv/nfsroot" = {
  #   device = "/dev/mapper/nfsroot";
  #   fsType = "ext4";
  # };
  # fileSystems."/srv/nfs" = {
  #   device = "/dev/mapper/nfs";
  #   fsType = "ext4";
  # };

  hardware.cpu.${cpu_bender hostname}.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}