# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod"];
      kernelModules = ["dm-snapshot"];
      luks.devices = {
        luksroot = {
          device = "/dev/disk/by-partlabel/LUKSROOT";
          preLVM = true;
          allowDiscards = true;
        };
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/yui-root";
    fsType = "ext4";
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-label/yui-nix";
    fsType = "ext4";
  };
  fileSystems."/var" = {
    device = "/dev/disk/by-label/yui-var";
    fsType = "ext4";
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-label/yui-home";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/yu-boot";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/dev/mapper/VolGroupYui-lvolswap";
      priority = 10;
    }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}