[k8s.settings]
notShow = true
serviceClusterIpRange = "10.100.0.0/16"
apiserverAddress = "10.10.100.100"      #
clusterCidr = "10.200.0.0/16"

[nodes.etcd]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["10.10.100.20", "10.10.100.21", "10.10.100.22"]

[nodes.loadbalancer]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["10.10.100.10", "10.10.100.11", "10.10.100.12"]

[nodes.controlplane]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["10.10.100.30", "10.10.100.31", "10.10.100.32"]

[nodes.worker]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["10.10.100.40", "10.10.100.41", "10.10.100.42"]

[nodes.proxy]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["10.10.100.50"]
