[liveimg.first-image]
system = "x86_64-linux"
user = "nixos"
hostname = "first-image"
[liveimg.second-image]
system = "x86_64-linux"
user = "nixos"
hostname = "second-image"
[liveimg.livecd]
system = "x86_64-linux"
user = "nixos"
hostname = "nixos-livecd"
[liveimg.netboot]
system = "x86_64-linux"
user = "nixos"
hostname = "nixos-netboot"

[switch.sks8300]
notShow = true
system = "x86_64-linux"
user = "renako"
hostname = "kaho"
manageIP = "172.16.10.31/24"
AS = "65011"
routerId = "10.10.10.31"
color = "green"

[switch.kaho]
system = "x86_64-linux"
user = "renako"
hostname = "kaho"
manageIP = "172.16.10.32/24"
routerId = "10.10.10.32"
AS = "65012"
l2vpnListenRange = "10.10.10.0/24"
color = "green"

[compute.virtualIPs]
notShom = true
[compute.virtualIPs.linstor]
address = "10.10.10.100"
cidr = "32"
[compute.virtualIPs.nfs]
address = "10.10.10.101"
cidr = "32"
[compute.virtualIPs.incus]
address = "172.16.10.102"
cidr = "24"

[compute.ajisai]
system = "x86_64-linux"
user = "renako"
hostname = "ajisai"
manageIP = "172.16.10.50/24"
routerId = "10.10.10.50"
AS = "65050"
color = "blue"
[compute.mai]
system = "x86_64-linux"
user = "renako"
hostname = "mai"
manageIP = "172.16.10.51/24"
routerId = "10.10.10.51"
AS = "65051"
color = "blue"
[compute.satsuki]
system = "x86_64-linux"
user = "renako"
hostname = "satsuki"
manageIP = "172.16.10.52/24"
routerId = "10.10.10.52"
AS = "65052"
color = "blue"
# [compute.haruna]
# system = "x86_64-linux"
# user = "renako"
# hostname = "haruna"
# address = ["172.16.10.53/24"]
# routerId = "10.10.10.53"
# AS = "65053"

[microvm.borderLeaf]
system = "x86_64-linux"
user = "renako"
hostname = "borderLeaf"
routerId = "10.10.10.253"
AS = "65020"
[microvm.borderRouter]
system = "x86_64-linux"
user = "renako"
hostname = "borderRouter"
routerId = "10.10.10.254"
AS = "64512"

[mngr.phikun]
system = "x86_64-linux"
user = "amaori"
hostname = "phikun"
manageIP = "172.16.10.10/24"
[mngr.image-server]
system = "x86_64-linux"
user = "amaori"
hostname = "fourkun"
manageIP = "172.16.10.11/24"
[mngr.image-server.dnsmasq]
rangeStart = "150"
port = "53"
server = []
[mngr.fake-isp]
system = "x86_64-linux"
user = "amaori"
hostname = "fake-isp"
manageIP = "172.16.10.1/24"
