[collection-kubernetes-core]
src.github_tag = 'ansible-collections/kubernetes.core'
fetch.url = "https://galaxy.ansible.com/download/kubernetes-core-$ver.tar.gz"

[collection-community-general]
src.github_tag = 'ansible-collections/community.general'
fetch.url = "https://galaxy.ansible.com/download/community-general-$ver.tar.gz"

[collection-community-openwrt]
src.github_tag = 'ansible-collections/community.openwrt'
fetch.url = "https://galaxy.ansible.com/download/community-openwrt$ver.tar.gz"
