[dnsmasq.pxe]
dhcpRelay = false
rangeStart = "20"
server = []       # if not empty, will use upstream DNS
port = 53         # if 0, dnsmasq will not provide DNS service
[dnsmasq.pxe.network]
suffix = "1"
baseIP = "10.10.0."
baseIPv6 = "fd42:3a98:dc40:10::"
ipPrefix = "/24"
ipv6Prefix = "/64"

[dnsmasq.kexec1]
dhcpRelay = false
rangeStart = "20"
server = []       # if not empty, will use upstream DNS
port = 53         # if 0, dnsmasq will not provide DNS service
[dnsmasq.kexec1.network]
suffix = "1"
baseIP = "10.20.0."
baseIPv6 = "fd42:3a98:dc40:20::"
ipPrefix = "/24"
ipv6Prefix = "/64"
id = "210"

[dnsmasq.kexec2]
dhcpRelay = false
rangeStart = "20"
server = []       # if not empty, will use upstream DNS
port = 53         # if 0, dnsmasq will not provide DNS service
[dnsmasq.kexec2.network]
suffix = "1"
baseIP = "10.30.0."
baseIPv6 = "fd42:3a98:dc40:30::"
ipPrefix = "/24"
ipv6Prefix = "/64"
id = "220"
