[k8s.settings]
notShow = true
serviceClusterIpRange = "10.100.0.0/16"
apiserverAddress = "172.16.100.100"     #
clusterCidr = "10.200.0.0/16"

[nodes.etcd]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.100.20", "172.16.100.21", "172.16.100.22"]

[nodes.loadbalancer]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.100.10", "172.16.100.11", "172.16.100.12"]

[nodes.controlplane]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.100.30", "172.16.100.31", "172.16.100.32"]

[nodes.worker]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.100.40", "172.16.100.41", "172.16.100.42"]

[nodes.storage-worker]
system = "x86_64-linux"
user = "nixos"

[nodes.ceph-worker]
notShow = true
nodeIPs = [
    # for ceph
    "172.16.100.40",
    "172.16.100.41",
    "172.16.100.42",
]
[nodes.piraeus-worker]
notShow = true
nodeIPs = [
    # for piraeus-operator
    "172.16.100.50",
    "172.16.100.51",
    "172.16.100.52",
]

[proxy.proxy]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.100.50"]

[vault.vault]
system = "x86_64-linux"
user = "nixos"
nodeIPs = ["172.16.11.10", "172.16.11.11", "172.16.11.12"]
vip = "172.16.11.1"

#################################################
# shared image
#################################################
[shared.dhcp]
system = "x86_64-linux"
user = "cocoa"
hostname = "chino"
manageIP = "172.16.1.254"
manageIPPrefix = "24"
[shared.resolver]
system = "x86_64-linux"
user = "cocoa"
hostname = "chiya"
manageIP = "172.16.1.1"
manageIPPrefix = "24"
acl = [
    "172.16.100.0/24 allow", # k8s nodes
    "172.16.1.0/24 allow",   # shared nodes
]
[shared.dns]
system = "x86_64-linux"
user = "cocoa"
hostname = "rize"
manageIP = "172.16.1.2"
manageIPPrefix = "24"
[shared.adblock]
system = "x86_64-linux"
user = "cocoa"
hostname = "syaro"
manageIP = "172.16.1.3"
manageIPPrefix = "24"
