apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https:/10.10.100.100
  project: default
  source:
    path: ./manifests/dev/cilium
    repoURL: https://github.com/misumisumi/ProjectQueentet-manufests.git
    targetRevision: develop
  syncPolicy: {}
