# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cilium = {
    pname = "cilium";
    version = "v1.19.5";
    src = fetchFromGitHub {
      owner = "cilium";
      repo = "cilium";
      rev = "v1.19.5";
      fetchSubmodules = false;
      sha256 = "sha256-0/GlsmRG6YuHJ8ROoVrCiksFf1+wokxUEzO6V6gvme4=";
    };
  };
  gateway-api = {
    pname = "gateway-api";
    version = "v1.6.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "gateway-api";
      rev = "v1.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-Cu6yYwLaY24fmiMfHZ0AsGfAH8MnnIzHvzvne4V5/k4=";
    };
  };
}
