{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.networking.nftables;

  tableSubmodule =
    { name, ... }:
    {
      options = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable this table.";
        };
        name = lib.mkOption {
          type = lib.types.str;
          description = "Table name.";
        };
        content = lib.mkOption {
          type = lib.types.lines;
          description = "The table content.";
        };
        family = lib.mkOption {
          description = "Table family.";
          type = lib.types.enum [
            "ip"
            "ip6"
            "inet"
            "arp"
            "bridge"
            "netdev"
          ];
        };
      };
      config = {
        name = lib.mkDefault name;
      };
    };

  # Generate the complete ruleset as upstream does, but for host-delegated we
  # write it directly to /etc/nftables.conf via environment.etc instead of
  # managing it via a systemd.service that would shadow host's /lib/systemd/system/nftables.service.
  enabledTables = lib.filterAttrs (_: table: table.enable) cfg.tables;

  deletionsContent =
    if cfg.flushRuleset then
      "flush ruleset"
    else
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (_: table: ''
          table ${table.family} ${table.name}
          delete table ${table.family} ${table.name}
        '') enabledTables
      )
      + lib.optionalString (cfg.extraDeletions != "") "\n${cfg.extraDeletions}";

  tablesContent = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (_: table: ''
      table ${table.family} ${table.name} {
        ${table.content}
      }
    '') enabledTables
  );

  rulesetContent = lib.concatStringsSep "\n" (
    lib.filter (s: s != "") [
      deletionsContent
      tablesContent
      cfg.ruleset
      (
        if cfg.rulesetFile != null then
          if cfg.flattenRulesetFile then
            builtins.readFile cfg.rulesetFile
          else
            ''include "${cfg.rulesetFile}"''
        else
          ""
      )
    ]
  );

  # The file that will be placed in /etc/nftables.conf. Upstream uses a script
  # that is executed by systemd.services.nftables; for host-delegated we just
  # write the plain ruleset (with deletions) to /etc and let host's nftables.service
  # (apt) load it. The deletions are included at the top so a reload is atomic
  # when host runs `nft -f /etc/nftables.conf`.
  rulesetFile = pkgs.writeText "nftables.conf" ''
    # Generated by dgx-spark/nftables.nix (host-delegated, does not shadow host systemd)
    # To apply: `nft -f /etc/nftables.conf` or `systemctl restart nftables` (host)
    ${rulesetContent}
  '';
in
{
  ###### Host-delegated nftables for Ubuntu/DGX Spark
  # Port of nixos/modules/services/networking/nftables.nix but without
  # boot.blacklistedKernelModules and without systemd.services.nftables that
  # would shadow host's /lib/systemd/system/nftables.service (apt:nftables).
  # Instead we only manage declarative config in /etc/nftables.conf via environment.etc
  # and leave host's systemd unit (and ufw) authoritative.

  options = {
    networking.nftables = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Whether to enable nftables declarative ruleset on Ubuntu/DGX host.

          Host-delegated: only writes `/etc/nftables.conf` (and optionally
          `/etc/nftables/*.nft` via tables) via `environment.etc`. Does NOT create
          `systemd.services.nftables` that would shadow host's `apt:nftables` unit,
          and does NOT blacklist `ip_tables` (host kernel is managed by Ubuntu).

          Host's `nftables.service` (if enabled) will load `/etc/nftables.conf` on boot.
          After a switch, run `nft -f /etc/nftables.conf` or `systemctl restart nftables` manually.
          If `ufw` is active, ensure rules do not conflict (ufw also uses nft/iptables).
        '';
      };

      checkRuleset = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Run `nft --check` on the ruleset during build (sandboxed).";
      };

      checkRulesetRedirects = lib.mkOption {
        type = lib.types.addCheck (lib.types.attrsOf lib.types.path) (
          attrs: lib.all lib.types.path.check (lib.attrNames attrs)
        );
        default = { };
        defaultText = lib.literalExpression "{ }";
        description = "Paths to intercept with libredirect during `nft --check`. Leave empty for system-manager (no /etc/hosts etc. in store).";
      };

      preCheckRuleset = lib.mkOption {
        type = lib.types.lines;
        default = "";
        example = "sed 's/skgid meadow/skgid root/g' -i ruleset.conf";
        description = "Script run before `nft --check` (sandbox).";
      };

      flushRuleset = lib.mkEnableOption "flushing the entire ruleset on each reload";

      extraDeletions = lib.mkOption {
        type = lib.types.lines;
        default = "";
        example = ''
          table inet some-table;
          delete table inet some-table;
        '';
        description = "Extra deletion commands run before each reload.";
      };

      ruleset = lib.mkOption {
        type = lib.types.lines;
        default = "";
        example = ''
          table inet filter {
            chain input {
              type filter hook input priority 0;
              iifname lo accept
              ct state {established, related} accept
              tcp dport 22 accept
              counter drop
            }
            chain output { type filter hook output priority 0; accept }
            chain forward { type filter hook forward priority 0; accept }
          }
        '';
        description = "Raw ruleset (nft -f format). Written to /etc/nftables.conf together with tables.";
      };

      rulesetFile = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "File to include (via `include` or `readFile` if flatten).";
      };

      flattenRulesetFile = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Use `builtins.readFile` instead of `include` for rulesetFile.";
      };

      tables = lib.mkOption {
        type = lib.types.attrsOf (lib.types.submodule tableSubmodule);
        default = { };
        description = "Tables to add (each generates `table <family> <name> { <content> }` with auto-delete).";
        example = {
          filter = {
            family = "inet";
            content = ''
              chain input {
                type filter hook input priority 0;
                iifname lo accept
                ct state {established, related} accept
                tcp dport 22 accept
                counter drop
              }
              chain output { type filter hook output priority 0; accept }
              chain forward { type filter hook forward priority 0; accept }
            '';
          };
        };
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # Do NOT blacklist ip_tables – host kernel is Ubuntu-managed.
    # Do NOT add nftables to boot.blacklistedKernelModules.

    environment.systemPackages = [ pkgs.nftables ];

    # Default flush behavior: same as upstream, but without stateVersion check for system-manager.
    # Host-delegated: flush only if user explicitly set flushRuleset or provided ruleset.
    # We keep upstream's default (flush if ruleset/rulesetFile non-empty) as mkDefault.
    networking.nftables.flushRuleset = lib.mkDefault (
      cfg.ruleset != "" || cfg.rulesetFile != null || cfg.tables != { }
    );

    environment.etc = {
      "nftables.conf" = {
        source = rulesetFile;
        mode = "0644";
      };
    };

    systemd.tmpfiles.rules = [
      "d /etc/nftables 0755 root root -"
    ];

    # Build-time check similar to upstream's checkPhase, but as system.checks for system-manager.
    system.checks = lib.optional cfg.checkRuleset (
      pkgs.runCommand "check-nftables-ruleset"
        {
          nativeBuildInputs = [ pkgs.nftables ];
        }
        ''
          cp ${rulesetFile} ruleset.conf
          ${cfg.preCheckRuleset}
          ${lib.optionalString (cfg.checkRulesetRedirects != { }) ''
            export NIX_REDIRECTS=${
              lib.escapeShellArg (
                lib.concatStringsSep ":" (lib.mapAttrsToList (n: v: "${n}=${v}") cfg.checkRulesetRedirects)
              )
            }
            export LD_PRELOAD="${pkgs.libredirect}/lib/libredirect.so"
          ''}
          ${pkgs.nftables}/bin/nft --check --file ruleset.conf
          touch $out
        ''
    );

    warnings = [
      "dgx-spark.nftables: host-delegated mode – /etc/nftables.conf is declarative, but no systemd.services.nftables is created to avoid shadowing host's /lib/systemd/system/nftables.service (apt). After switch, run `nft -f /etc/nftables.conf` or `systemctl restart nftables` manually. If ufw is active, ensure nft rules do not conflict with ufw's iptables-nft rules."
    ];
  };
}
