{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.networking.wg-quick;

  # Interface and peer options — port of nixos/modules/services/networking/wg-quick.nix
  # but host-delegated: only manages /etc/wireguard/*.conf via environment.etc
  # and systemd.services.wg-quick-* without shadowing host's systemd units.
  interfaceOpts =
    { ... }:
    {
      options = {
        type = mkOption {
          example = "amneziawg";
          default = "wireguard";
          type = types.enum [
            "wireguard"
            "amneziawg"
          ];
          description = "The type of the interface.";
        };

        configFile = mkOption {
          example = "/secret/wg0.conf";
          default = null;
          type = with types; nullOr str;
          description = ''
            wg-quick .conf file. If set, overrides all other interface options
            and uses the given file directly (via PrivateTmp bind).
          '';
        };

        address = mkOption {
          example = [ "192.168.2.1/24" ];
          default = [ ];
          type = with types; listOf str;
          description = "The IP addresses of the interface.";
        };

        autostart = mkOption {
          description = "Whether to bring up this interface automatically during boot.";
          default = true;
          example = false;
          type = types.bool;
        };

        dns = mkOption {
          example = [ "192.168.2.2" ];
          default = [ ];
          type = with types; listOf str;
          description = "The IP addresses of DNS servers to configure.";
        };

        privateKey = mkOption {
          example = "yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=";
          type = with types; nullOr str;
          default = null;
          description = "Base64 private key (world-readable Nix store). Prefer privateKeyFile.";
        };

        generatePrivateKeyFile = mkOption {
          default = false;
          type = types.bool;
          description = "Automatically generate a private key at privateKeyFile.";
        };

        privateKeyFile = mkOption {
          example = "/private/wireguard_key";
          type = with types; nullOr str;
          default = null;
          description = "File pointing to private key as generated by wg genkey.";
        };

        listenPort = mkOption {
          default = null;
          type = with types; nullOr int;
          example = 51820;
          description = "16-bit port for listening.";
        };

        preUp = mkOption {
          example = literalExpression ''"''${pkgs.iproute2}/bin/ip netns add foo"'';
          default = "";
          type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
          description = "Commands called at the start of the interface setup.";
        };

        preDown = mkOption {
          example = literalExpression ''"''${pkgs.iproute2}/bin/ip netns del foo"'';
          default = "";
          type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
          description = "Command called before the interface is taken down.";
        };

        postUp = mkOption {
          example = literalExpression ''"''${pkgs.iproute2}/bin/ip netns add foo"'';
          default = "";
          type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
          description = "Commands called after the interface setup.";
        };

        postDown = mkOption {
          example = literalExpression ''"''${pkgs.iproute2}/bin/ip netns del foo"'';
          default = "";
          type = with types; coercedTo (listOf str) (concatStringsSep "\n") lines;
          description = "Command called after the interface is taken down.";
        };

        table = mkOption {
          example = "main";
          default = null;
          type = with types; nullOr str;
          description = "Kernel routing table for associated routes.";
        };

        mtu = mkOption {
          example = 1248;
          default = null;
          type = with types; nullOr int;
          description = "MTU for the wireguard interface.";
        };

        peers = mkOption {
          default = [ ];
          description = "Peers linked to the interface.";
          type = with types; listOf (submodule peerOpts);
        };

        extraOptions = mkOption {
          type =
            with types;
            attrsOf (oneOf [
              str
              int
            ]);
          default = { };
          example = {
            Jc = 5;
            Jmin = 10;
          };
          description = "Extra options to append to the interface section (AmneziaWG).";
        };
      };
    };

  peerOpts = {
    options = {
      publicKey = mkOption {
        example = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=";
        type = types.str;
        description = "The base64 public key of the peer.";
      };

      presharedKey = mkOption {
        default = null;
        example = "rVXs/Ni9tu3oDBLS4hOyAUAa1qTWVA3loR8eL20os3I=";
        type = with types; nullOr str;
        description = "Base64 preshared key.";
      };

      presharedKeyFile = mkOption {
        default = null;
        example = "/private/wireguard_psk";
        type = with types; nullOr str;
        description = "File pointing to preshared key.";
      };

      allowedIPs = mkOption {
        example = [
          "10.192.122.3/32"
          "10.192.124.1/24"
        ];
        type = with types; listOf str;
        description = "List of allowed IPs for this peer.";
      };

      endpoint = mkOption {
        default = null;
        example = "demo.wireguard.io:12913";
        type = with types; nullOr str;
        description = "Endpoint IP or hostname of the peer.";
      };

      persistentKeepalive = mkOption {
        default = null;
        type = with types; nullOr int;
        example = 25;
        description = "Persistent keepalive interval (1-65535).";
      };
    };
  };

  writeScriptFile = name: text: ((pkgs.writeShellScriptBin name text) + "/bin/${name}");

  generatePrivateKeyScript = privateKeyFile: wgBin: ''
    set -e
    mkdir -p --mode 0755 "${dirOf privateKeyFile}"
    if [ ! -f "${privateKeyFile}" ]; then
      (set -e; umask 077; ${wgBin} genkey > "${privateKeyFile}")
    fi
  '';

  generateUnit =
    name: values:
    assert assertMsg (
      values.configFile != null || ((values.privateKey != null) != (values.privateKeyFile != null))
    ) "Only one of privateKey, configFile or privateKeyFile may be set";
    assert assertMsg (
      values.generatePrivateKeyFile == false || values.privateKeyFile != null
    ) "generatePrivateKeyFile requires privateKeyFile to be set";
    let
      wgBin =
        {
          wireguard = "wg";
          amneziawg = "awg";
        }
        .${values.type};
      wgPackage =
        {
          wireguard = pkgs.wireguard-tools;
          amneziawg = pkgs.amneziawg-tools;
        }
        .${values.type};
      generateKeyScriptFile =
        if values.generatePrivateKeyFile then
          writeScriptFile "generatePrivateKey.sh" (generatePrivateKeyScript values.privateKeyFile wgBin)
        else
          null;
      preUpFile = if values.preUp != "" then writeScriptFile "preUp.sh" values.preUp else null;
      postUp =
        optional (
          values.privateKeyFile != null
        ) "${wgBin} set ${name} private-key <(cat ${values.privateKeyFile})"
        ++ (concatMap (
          peer:
          optional (
            peer.presharedKeyFile != null
          ) "${wgBin} set ${name} peer ${peer.publicKey} preshared-key <(cat ${peer.presharedKeyFile})"
        ) values.peers)
        ++ optional (values.postUp != "") values.postUp;
      postUpFile =
        if postUp != [ ] then
          writeScriptFile "postUp.sh" (concatMapStringsSep "\n" (line: line) postUp)
        else
          null;
      preDownFile = if values.preDown != "" then writeScriptFile "preDown.sh" values.preDown else null;
      postDownFile =
        if values.postDown != "" then writeScriptFile "postDown.sh" values.postDown else null;
      configDir = pkgs.writeTextFile {
        name = "config-${name}";
        executable = false;
        destination = "/${name}.conf";
        text = ''
          [interface]
          ${concatMapStringsSep "\n" (address: "Address = ${address}") values.address}
          ${concatMapStringsSep "\n" (dns: "DNS = ${dns}") values.dns}
        ''
        + optionalString (values.table != null) "Table = ${values.table}\n"
        + optionalString (values.mtu != null) "MTU = ${toString values.mtu}\n"
        + optionalString (values.privateKey != null) "PrivateKey = ${values.privateKey}\n"
        + optionalString (values.listenPort != null) "ListenPort = ${toString values.listenPort}\n"
        + optionalString (generateKeyScriptFile != null) "PreUp = ${generateKeyScriptFile}\n"
        + optionalString (preUpFile != null) "PreUp = ${preUpFile}\n"
        + optionalString (postUpFile != null) "PostUp = ${postUpFile}\n"
        + optionalString (preDownFile != null) "PreDown = ${preDownFile}\n"
        + optionalString (postDownFile != null) "PostDown = ${postDownFile}\n"
        + concatLines (mapAttrsToList (n: v: "${n} = ${toString v}") values.extraOptions)
        + concatMapStringsSep "\n" (
          peer:
          assert assertMsg (
            !((peer.presharedKeyFile != null) && (peer.presharedKey != null))
          ) "Only one of presharedKey or presharedKeyFile may be set";
          "[Peer]\n"
          + "PublicKey = ${peer.publicKey}\n"
          + optionalString (peer.presharedKey != null) "PresharedKey = ${peer.presharedKey}\n"
          + optionalString (peer.endpoint != null) "Endpoint = ${peer.endpoint}\n"
          + optionalString (
            peer.persistentKeepalive != null
          ) "PersistentKeepalive = ${toString peer.persistentKeepalive}\n"
          + optionalString (peer.allowedIPs != [ ]) "AllowedIPs = ${concatStringsSep "," peer.allowedIPs}\n"
        ) values.peers;
      };
      configPath = if values.configFile != null then "/tmp/${name}.conf" else "${configDir}/${name}.conf";
    in
    nameValuePair "wg-quick-${name}" {
      description = "wg-quick WireGuard Tunnel - ${name} (host-delegated)";
      requires = [ "network-online.target" ];
      after = [
        "network.target"
        "network-online.target"
      ];
      wantedBy = optional values.autostart "multi-user.target";
      environment.DEVICE = name;
      # Host-delegated: include host's /usr/bin for wg-quick, iptables/nftables, resolvconf
      # and Nix's wireguard-tools for fallback. Use mkForce to ensure host paths are searched first.
      path = [
        {
          wireguard = pkgs.wireguard-tools;
          amneziawg = pkgs.amneziawg-tools;
        }
        .${values.type}
      ];
      environment.PATH = lib.mkForce "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${
        lib.makeBinPath [
          pkgs.wireguard-tools
          pkgs.kmod
          pkgs.iproute2
        ]
      }";
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        PrivateTmp = values.configFile != null;
      };
      script = ''
        ${optionalString (
          !config.boot.isContainer or false
        ) "${pkgs.kmod}/bin/modprobe ${values.type} || true"}
        ${optionalString (values.configFile != null) ''
          cp ${values.configFile} ${configPath}
        ''}
        ${wgBin}-quick up ${configPath}
      '';
      preStop = ''
        ${wgBin}-quick down ${configPath}
      '';
    };

in
{
  ###### Host-delegated wg-quick for Ubuntu/DGX Spark
  # Port of nixos/modules/services/networking/wg-quick.nix but host-delegated:
  # - Only manages wireguard config via environment.etc? No, wg-quick generates config in store and uses it directly via ExecStart.
  # - Creates systemd.services.wg-quick-* without conflicting with host's NetworkManager/systemd-networkd.
  # - Host's /etc/wireguard/*.conf is not declarative unless configFile is used; generated config lives in Nix store.
  # - Requires wireguard kernel module (boot.kernelModules) and wireguard-tools (apt or nix). Host's apt wireguard-tools is preferred.

  options.networking.wg-quick = {
    interfaces = mkOption {
      description = "WireGuard interfaces via wg-quick (host-delegated).";
      default = { };
      example = {
        wg0 = {
          address = [ "192.168.20.4/24" ];
          privateKeyFile = "/private/wireguard_key";
          peers = [
            {
              allowedIPs = [ "192.168.20.1/32" ];
              publicKey = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=";
              endpoint = "demo.wireguard.io:12913";
            }
          ];
        };
      };
      type = with types; attrsOf (submodule interfaceOpts);
    };
  };

  config = mkIf (cfg.interfaces != { }) {
    # Ensure wireguard kernel module is loaded via host-delegated boot (50-system-manager.conf)
    # We don't set boot.extraModulePackages (host kernel), just ensure module load via boot.kernelModules.
    # The module will be loaded by systemd-modules-load.service (dgx-spark/boot.nix).

    warnings = [
      "dgx-spark.wg-quick: host-delegated – wg-quick tunnels are managed via systemd.services.wg-quick-*. After switch, interfaces are brought up via 'wg-quick up'. Host's /etc/wireguard/*.conf is not declarative unless configFile is used. Ensure wireguard-tools is installed via apt.packages."
    ];

    systemd.services = mapAttrs' generateUnit cfg.interfaces;

    # Prevent networkd from clearing wg-quick routes when restarted
    systemd.network.config.networkConfig.ManageForeignRoutingPolicyRules = lib.mkDefault false;
    systemd.network.wait-online.ignoredInterfaces = builtins.attrNames cfg.interfaces;
  };
}
