name: Format check
on:
  push:
    branch-ignore:
      - "update_flake_lock_action"
    tags:
      - "*"
    paths:
      - "**.nix"
  pull_request:

jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run nixpkgs#nixpkgs-fmt -- --check $(find ./ -type f -name "*.nix" | grep -v generated.nix)
